steps:
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']